[package]
name = "ercp_basic"
version = "0.1.0"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]
edition = "2018"

[dependencies]
embedded-crc-macros = "0.1.0"
embedded-hal = { version = "0.2.5", optional = true }
ercp_basic_macros = { path = "macros" }
nb = { version = "1.0.0", optional = true }
serialport = { version = "4.0.1", optional = true }

[build-dependencies]
embedded-crc-macros = "0.1.0"

[dev-dependencies]
proptest = "1.0.0"

[features]
embedded = ["embedded-hal", "nb"]
host = ["serialport", "std"]
std = []

[workspace]
members = [
    "macros",
]
