[package]
name = "ercp_basic_macros"
version = "0.1.0"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]
edition = "2018"

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.72", features = ["full"] }
proc-macro2 = "1.0.27"

[lib]
proc-macro = true
